# Generated by Django 4.1.1 on 2022-10-09 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prefer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='Nodata', help_text='유저 id', max_length=10, unique=True)),
                ('prefer_modern', models.IntegerField(default=0, help_text='모던 가중치')),
                ('prefer_natural', models.IntegerField(default=0, help_text='네츄럴 가중치')),
                ('prefer_classic', models.IntegerField(default=0, help_text='클래식 가중치')),
                ('prefer_industry', models.IntegerField(default=0, help_text='인더스트리 가중치')),
                ('prefer_asia', models.IntegerField(default=0, help_text='아시아 가중치')),
                ('prefer_provence', models.IntegerField(default=0, help_text='프로방스 가중치')),
                ('prefer_unique', models.IntegerField(default=0, help_text='유니크 가중치')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='Nodata', help_text='유저 id', max_length=10, unique=True)),
                ('password', models.CharField(default='Nodata', help_text='유저 비밀번호', max_length=10)),
                ('address', models.CharField(default='Nodata', help_text='유저 주소', max_length=10)),
                ('nickname', models.CharField(default='Nodata', help_text='유저 닉네임', max_length=10, unique=True)),
            ],
        ),
    ]
