# Generated by Django 4.1.1 on 2022-10-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_id', models.CharField(default='Nodata', help_text='유저 id', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(default='Nodata', help_text='유저 비밀번호', max_length=10)),
                ('address', models.CharField(default='Nodata', help_text='유저 주소', max_length=10)),
                ('nickname', models.CharField(default='Nodata', help_text='유저 닉네임', max_length=10, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
