# Generated by Django 4.1.1 on 2022-10-11 01:42

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lodging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodging_name', models.CharField(help_text='숙소명', max_length=10)),
                ('lodging_address', models.TextField(help_text='숙소 주소')),
                ('tag', models.IntegerField(help_text='태그')),
                ('lodging_img1', models.TextField(help_text='숙소 이미지1')),
                ('lodging_img2', models.TextField(help_text='숙소 이미지2')),
                ('lodging_img3', models.TextField(help_text='숙소 이미지3')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_date', models.DateField(auto_now_add=True, help_text='숙소 좋아요 누른 시점')),
                ('lodging_id', models.ForeignKey(on_delete=django.db.models.fields.CharField, to='lodgings.lodging')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.fields.CharField, to='accounts.account')),
            ],
        ),
    ]
