# Generated by Django 4.1.1 on 2022-10-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodgings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='lodging_id',
            field=models.IntegerField(help_text='lodging의 index'),
        ),
        migrations.DeleteModel(
            name='Lodging',
        ),
    ]
